#!/bin/bash
# Setup .env.local for Screenshot Processing
#
# This script helps configure the minimum required environment variables
# for running screenshot batch processing

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env.local"
TEMPLATE_FILE="$PROJECT_ROOT/.env.local.template"

echo "========================================"
echo "Screenshot Environment Setup"
echo "========================================"
echo ""

# Check if template exists
if [ ! -f "$TEMPLATE_FILE" ]; then
    echo "ERROR: .env.local.template not found!"
    exit 1
fi

# Backup existing .env.local if it exists
if [ -f "$ENV_FILE" ]; then
    BACKUP_FILE="$ENV_FILE.backup.$(date +%s)"
    echo "Backing up existing .env.local to: $BACKUP_FILE"
    cp "$ENV_FILE" "$BACKUP_FILE"
    echo ""
fi

# Read Cloudflare credentials
echo "Enter your Cloudflare credentials:"
echo "(Get these from: https://dash.cloudflare.com/)"
echo ""

read -p "Cloudflare Account ID: " CLOUDFLARE_ACCOUNT_ID
read -p "Cloudflare API Token: " CLOUDFLARE_API_TOKEN

echo ""
echo "Generating secrets..."

# Generate secrets if not already set
BETTER_AUTH_SECRET=$(openssl rand -base64 32)
CRON_SECRET=$(openssl rand -hex 32)

echo "Done!"
echo ""

# Create .env.local with minimal required config
cat > "$ENV_FILE" << EOF
# Dobacklinks Environment Configuration
# Auto-generated by setup-env-for-screenshots.sh

# -----------------------------------------------------------------------------
# Site info
# -----------------------------------------------------------------------------
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_PRICING_PATH="/pricing"
NEXT_PUBLIC_OPTIMIZED_IMAGES=false
NEXT_PUBLIC_LOGIN_MODE='dialog'

# -----------------------------------------------------------------------------
# Database (VPS Supabase)
# -----------------------------------------------------------------------------
DATABASE_URL=postgresql://postgres:postgres@93.127.133.204:54322/postgres

# -----------------------------------------------------------------------------
# Auth - better-auth
# -----------------------------------------------------------------------------
BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET

# -----------------------------------------------------------------------------
# Cloudflare Browser Rendering (for screenshots)
# -----------------------------------------------------------------------------
CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN

# Screenshot Settings
SCREENSHOT_VIEWPORT_WIDTH=1920
SCREENSHOT_VIEWPORT_HEIGHT=1080
SCREENSHOT_THUMBNAIL_WIDTH=400
SCREENSHOT_THUMBNAIL_HEIGHT=300
SCREENSHOT_FORMAT=webp
SCREENSHOT_QUALITY=80

# Batch Processing Settings
SCREENSHOT_BATCH_SIZE=8
SCREENSHOT_MAX_PROCESSING_TIME_MS=55000
SCREENSHOT_DELAY_BETWEEN_BATCHES_MS=800
SCREENSHOT_STAGGER_DELAY_MS=100
SCREENSHOT_CLAIM_TTL_MS=600000

# -----------------------------------------------------------------------------
# Cron Jobs
# -----------------------------------------------------------------------------
CRON_SECRET=$CRON_SECRET

# -----------------------------------------------------------------------------
# Email (Resend) - Optional
# -----------------------------------------------------------------------------
ADMIN_EMAIL=outreach@dobacklinks.com
ADMIN_NAME=Dobacklinks

# -----------------------------------------------------------------------------
# Node Environment
# -----------------------------------------------------------------------------
NODE_ENV=development
EOF

echo "✅ Environment file created: $ENV_FILE"
echo ""
echo "Configuration Summary:"
echo "  Database: postgresql://postgres:***@93.127.133.204:54322/postgres"
echo "  Cloudflare Account: ${CLOUDFLARE_ACCOUNT_ID:0:8}..."
echo "  Cloudflare Token: ${CLOUDFLARE_API_TOKEN:0:8}..."
echo "  Auth Secret: Generated (32 bytes)"
echo "  Cron Secret: Generated (64 chars)"
echo ""
echo "Next steps:"
echo "  1. Test status: pnpm tsx scripts/quick-screenshot-status.ts"
echo "  2. Dry run: ./scripts/run-screenshot-batch.sh --dry-run"
echo "  3. Start batch: ./scripts/run-screenshot-batch.sh --batch-size 30 --delay 12"
echo ""
